### ISSUE TITLE
const apiKey variable should be used

### ISSUE THREAD

**Issue by Wolfy7** [akk312000/Movie-Recommender#14]
There is a variable
`const apiKey = process.env.API_KEY;`
for the API Key but its not used, instead process.env.API_KEY is used.

![image](https://user-images.githubusercontent.com/16044116/135914245-887797cf-0896-485e-96a2-ad94bf14e758.png)

**Comment by akk312000** [comment]
Thanks for pointing that out @Wolfy7 . I'm merging this PR.🚀
