### ISSUE TITLE
The Navbar (nav-link) doesnt gets active 

### ISSUE THREAD

**Issue by Wolfy7** [akk312000/Movie-Recommender#16]
In the Navbar the Movies navbar item is always active.

 
![image](https://user-images.githubusercontent.com/16044116/135914944-85255c31-1265-4b04-9a55-6aa97dcea925.png)
![image](https://user-images.githubusercontent.com/16044116/135914966-5f202717-3686-4876-8001-0943f80f3e68.png)
![image](https://user-images.githubusercontent.com/16044116/135914981-648c1fc4-1ddf-4b94-b1f3-fbbc368306e7.png)

**Comment by akk312000** [comment]
Okay, I'm assigning this issue to you @Wolfy7.

**Comment by Wolfy7** [comment]
Ok, thanks. Will have take care of this
