### ISSUE TITLE
Make Website Mobile Responsive

### ISSUE THREAD

**Issue by akk312000** [akk312000/Movie-Recommender#3]
Cards are getting cropped up in mobile view

![image](https://user-images.githubusercontent.com/63864369/135481716-1352d79a-2e93-4351-8e5b-ca8bbfa84406.png)

Also Hamburger Menu-Icon gets onto the second row
![image](https://user-images.githubusercontent.com/63864369/135571791-c19c99ca-c5f6-418d-acc0-c044accfa05d.png)

**Comment by TheCodinggDude** [comment]
Can I work on this issue ?

**Comment by akk312000** [comment]
@TheCodinggDude Yeah go ahead!

**Comment by TheCodinggDude** [comment]
Hey @akk312000 I've opened a PR. Kindly review it and tell me if you need any more changes. Currently it looks like this.
![Screenshot 2021-10-03 234234](https://user-images.githubusercontent.com/71598671/135766320-50a8a562-2515-4e68-b54e-7be9ae1a2302.jpg)
.
