### ISSUE TITLE
Hamburger Menu Isn't Working Properly

### ISSUE THREAD

**Issue by akk312000** [akk312000/Movie-Recommender#4]
The Hamburger Menubar gets opened but does not collapse when clicked again

![image](https://user-images.githubusercontent.com/63864369/135484822-53b602e3-8b27-4ba2-884d-bca41b94000f.png)

**Comment by Xaconi** [comment]
hey @akk312000 can i work on this one?

**Comment by akk312000** [comment]
Yeah @Xaconi  go ahead!...I'm assigning this to you!

**Comment by akk312000** [comment]
Thanks for the PR @Xaconi
