### ISSUE TITLE
Change Background Image of Shows Page

### ISSUE THREAD

**Issue by akk312000** [akk312000/Movie-Recommender#7]
The main background image remains same whether you search for movie or a show, change the background image to 
another image like given below when the user clicks on Shows button. 

![bac](https://user-images.githubusercontent.com/63864369/135784149-a7dd0b69-4bba-44ee-9023-41d044ed598f.png)

Make sure to adjust the background gradient to match that of movies page.

**Comment by Wolfy7** [comment]
Can assigne this to me, please?
I will create a PR soon
